# Generated by Django 4.2.3 on 2023-07-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descriptions',
            new_name='description',
        ),
    ]
